function(gu2_select_backend backend)
    string(TOUPPER ${backend} backend)
    if(backend MATCHES "SDL2")
        set(GU2_BACKEND_LIB SDL2::SDL2 PARENT_SCOPE)
        set(GU2_BACKEND_ENUM 1 PARENT_SCOPE)
        set(GU2_BACKEND_SOURCE_FILE backend_sdl2.cpp PARENT_SCOPE)
    elseif(backend MATCHES "GLFW")
        set(GU2_BACKEND_LIB glfw PARENT_SCOPE)
        set(GU2_BACKEND_ENUM 2 PARENT_SCOPE)
        set(GU2_BACKEND_SOURCE_FILE backend_glfw.cpp PARENT_SCOPE)
    else()
        message(FATAL_ERROR "Unsupported OS interfacing backend specified: ${backend}")
        return()
    endif()

    message(STATUS "Selected GraphicsUtils2 OS interfacing backend: ${backend}")
    set(GU2_BACKEND ${backend} PARENT_SCOPE)
endfunction()
